version: '2'

services:
  app:
    image: challangeprogramma
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 5002:80
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=jamooiwachtwoorddeze
    - MYSQL_DATABASE=challenge-programma
    - MYSQL_USER=challenge-programma
    - MYSQL_PASSWORD=jaheelleukwachtwoordhebbenwehier!
    networks:
      - backend
networks:
  frontend:
  backend:
